server:
  port: 80

spring:
  application:
    name: beyond-library-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        ip: 172.20.57.241
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 180s
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: beyond-library-svc-account
          uri: lb://beyond-library-svc-account
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(.*), /api/$\1
            - Authentication
            - Authorization

management:
  server:
    port: 81
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:

logging:
  level:
    root: info
feign:
  circuitbreaker:
    enabled: true
  encoder:
    charset-from-content-type: true
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
