server:
  port: 9080
  servlet:
    context-path: /account

spring:
  application:
    name: beyond-library-svc-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.24.160.1:3306/beyond-library-account?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: beyond
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 172.24.160.1:8848
        ip: 172.24.160.1
